### ISSUE TITLE
A version with "standard" window controls?

### ISSUE THREAD

**Issue by CavaleriOmar** [Andereoo/Cortland#1]
I really like this CSS, especially since it's the only one that works perfectly with Proton in having the tab bar below the toolbar, while keeping the window control buttons elsewhere... and speaking of those buttons, would it be possible to have a version of the CSS that follows the theme in use on linux, as Firefox normally does?

I'm not very familiar, so knowing at least which lines to edit to do it myself would already be a big help

Translated with www.DeepL.com/Translator (free version)

**Comment by Andereoo** [comment]
Hello,

Yes, you can choose to use the system icons, but it will take some tweaking.

Open Cortland's `icons.css` file (should be under `chrome/Cortland/parts/`) and scroll to line 26 (it should say `/* Window Buttons */`). Delete that line and **everything** below it.

Then open the `csd.css` file and delete everything between lines 125 and 202. Delete line 120 (should say `-moz-appearance: none !important;`). That should be all you need. In order to align the buttons correctly, you may want to add some margins. Just add `margin: 4px !important;` below line 120. You may need to change that 4px value depending on your OS.

Hopefully this works for you!

**Comment by Andereoo** [comment]
@CavaleriOmar Does this work for you?
